# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/device2cloud/common/RemoteConfigurationResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oss.northbound.device2cloud.common import LocalConfiguration_pb2 as oss_dot_northbound_dot_device2cloud_dot_common_dot_LocalConfiguration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/device2cloud/common/RemoteConfigurationResponse.proto',
  package='oss.northbound',
  syntax='proto2',
  serialized_pb=_b('\nDoss/northbound/device2cloud/common/RemoteConfigurationResponse.proto\x12\x0eoss.northbound\x1a;oss/northbound/device2cloud/common/LocalConfiguration.proto\"\xfc\x01\n\x1bRemoteConfigurationResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12[\n\"remote_configuration_response_type\x18\x03 \x01(\x0e\x32/.oss.northbound.RemoteConfigurationResponseType\x12\x15\n\rfailureReason\x18\x04 \x01(\t\x12\x42\n\x12\x63onfiguration_info\x18\x05 \x03(\x0b\x32&.oss.northbound.LocalConfigurationInfo*\x9e\x01\n\x1fRemoteConfigurationResponseType\x12\x14\n\x10RCONFRT_RECEIVED\x10\x00\x12\x17\n\x13RCONFRT_FINISHED_OK\x10\x01\x12\x1b\n\x17RCONFRT_FINISHED_FAILED\x10\x02\x12\x13\n\x0fRCONFRT_TIMEOUT\x10\x03\x12\x1a\n\x16RCONFRT_INTERNAL_ERROR\x10\x04\x42\x64\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB RemoteConfigurationResponseProto')
  ,
  dependencies=[oss_dot_northbound_dot_device2cloud_dot_common_dot_LocalConfiguration__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_REMOTECONFIGURATIONRESPONSETYPE = _descriptor.EnumDescriptor(
  name='RemoteConfigurationResponseType',
  full_name='oss.northbound.RemoteConfigurationResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RCONFRT_RECEIVED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RCONFRT_FINISHED_OK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RCONFRT_FINISHED_FAILED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RCONFRT_TIMEOUT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RCONFRT_INTERNAL_ERROR', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=405,
  serialized_end=563,
)
_sym_db.RegisterEnumDescriptor(_REMOTECONFIGURATIONRESPONSETYPE)

RemoteConfigurationResponseType = enum_type_wrapper.EnumTypeWrapper(_REMOTECONFIGURATIONRESPONSETYPE)
RCONFRT_RECEIVED = 0
RCONFRT_FINISHED_OK = 1
RCONFRT_FINISHED_FAILED = 2
RCONFRT_TIMEOUT = 3
RCONFRT_INTERNAL_ERROR = 4



_REMOTECONFIGURATIONRESPONSE = _descriptor.Descriptor(
  name='RemoteConfigurationResponse',
  full_name='oss.northbound.RemoteConfigurationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='oss.northbound.RemoteConfigurationResponse.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='oss.northbound.RemoteConfigurationResponse.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote_configuration_response_type', full_name='oss.northbound.RemoteConfigurationResponse.remote_configuration_response_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failureReason', full_name='oss.northbound.RemoteConfigurationResponse.failureReason', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='configuration_info', full_name='oss.northbound.RemoteConfigurationResponse.configuration_info', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=402,
)

_REMOTECONFIGURATIONRESPONSE.fields_by_name['remote_configuration_response_type'].enum_type = _REMOTECONFIGURATIONRESPONSETYPE
_REMOTECONFIGURATIONRESPONSE.fields_by_name['configuration_info'].message_type = oss_dot_northbound_dot_device2cloud_dot_common_dot_LocalConfiguration__pb2._LOCALCONFIGURATIONINFO
DESCRIPTOR.message_types_by_name['RemoteConfigurationResponse'] = _REMOTECONFIGURATIONRESPONSE
DESCRIPTOR.enum_types_by_name['RemoteConfigurationResponseType'] = _REMOTECONFIGURATIONRESPONSETYPE

RemoteConfigurationResponse = _reflection.GeneratedProtocolMessageType('RemoteConfigurationResponse', (_message.Message,), dict(
  DESCRIPTOR = _REMOTECONFIGURATIONRESPONSE,
  __module__ = 'oss.northbound.device2cloud.common.RemoteConfigurationResponse_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.RemoteConfigurationResponse)
  ))
_sym_db.RegisterMessage(RemoteConfigurationResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB RemoteConfigurationResponseProto'))
# @@protoc_insertion_point(module_scope)
