# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/device2cloud/common/RemoteUpgradeResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/device2cloud/common/RemoteUpgradeResponse.proto',
  package='oss.northbound',
  syntax='proto2',
  serialized_pb=_b('\n>oss/northbound/device2cloud/common/RemoteUpgradeResponse.proto\x12\x0eoss.northbound\"\xc0\x01\n\x15RemoteUpgradeResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12O\n\x1cremote_upgrade_response_type\x18\x03 \x01(\x0e\x32).oss.northbound.RemoteUpgradeResponseType\x12\x18\n\x10software_version\x18\x04 \x01(\t\x12\x15\n\rfailureReason\x18\x05 \x01(\t*\x9f\x02\n\x19RemoteUpgradeResponseType\x12\x11\n\rRURT_RECEIVED\x10\x00\x12\x17\n\x13RURT_START_DOWNLOAD\x10\x01\x12\x14\n\x10RURT_DOWNLOAD_OK\x10\x02\x12\x18\n\x14RURT_DOWNLOAD_FAILED\x10\x03\x12\x16\n\x12RURT_START_UPGRADE\x10\x04\x12\x14\n\x10RURT_FINISHED_OK\x10\x05\x12\x18\n\x14RURT_FINISHED_FAILED\x10\x06\x12\x19\n\x15RURT_RECEIVED_TIMEOUT\x10\x07\x12\x19\n\x15RURT_FINISHED_TIMEOUT\x10\x08\x12\x0f\n\x0bRURT_REJECT\x10\t\x12\x17\n\x13RURT_INTERNAL_ERROR\x10\nB^\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\x1aRemoteUpgradeResponseProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_REMOTEUPGRADERESPONSETYPE = _descriptor.EnumDescriptor(
  name='RemoteUpgradeResponseType',
  full_name='oss.northbound.RemoteUpgradeResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RURT_RECEIVED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RURT_START_DOWNLOAD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RURT_DOWNLOAD_OK', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RURT_DOWNLOAD_FAILED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RURT_START_UPGRADE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RURT_FINISHED_OK', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RURT_FINISHED_FAILED', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RURT_RECEIVED_TIMEOUT', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RURT_FINISHED_TIMEOUT', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RURT_REJECT', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RURT_INTERNAL_ERROR', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=278,
  serialized_end=565,
)
_sym_db.RegisterEnumDescriptor(_REMOTEUPGRADERESPONSETYPE)

RemoteUpgradeResponseType = enum_type_wrapper.EnumTypeWrapper(_REMOTEUPGRADERESPONSETYPE)
RURT_RECEIVED = 0
RURT_START_DOWNLOAD = 1
RURT_DOWNLOAD_OK = 2
RURT_DOWNLOAD_FAILED = 3
RURT_START_UPGRADE = 4
RURT_FINISHED_OK = 5
RURT_FINISHED_FAILED = 6
RURT_RECEIVED_TIMEOUT = 7
RURT_FINISHED_TIMEOUT = 8
RURT_REJECT = 9
RURT_INTERNAL_ERROR = 10



_REMOTEUPGRADERESPONSE = _descriptor.Descriptor(
  name='RemoteUpgradeResponse',
  full_name='oss.northbound.RemoteUpgradeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='oss.northbound.RemoteUpgradeResponse.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='oss.northbound.RemoteUpgradeResponse.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote_upgrade_response_type', full_name='oss.northbound.RemoteUpgradeResponse.remote_upgrade_response_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='software_version', full_name='oss.northbound.RemoteUpgradeResponse.software_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failureReason', full_name='oss.northbound.RemoteUpgradeResponse.failureReason', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=275,
)

_REMOTEUPGRADERESPONSE.fields_by_name['remote_upgrade_response_type'].enum_type = _REMOTEUPGRADERESPONSETYPE
DESCRIPTOR.message_types_by_name['RemoteUpgradeResponse'] = _REMOTEUPGRADERESPONSE
DESCRIPTOR.enum_types_by_name['RemoteUpgradeResponseType'] = _REMOTEUPGRADERESPONSETYPE

RemoteUpgradeResponse = _reflection.GeneratedProtocolMessageType('RemoteUpgradeResponse', (_message.Message,), dict(
  DESCRIPTOR = _REMOTEUPGRADERESPONSE,
  __module__ = 'oss.northbound.device2cloud.common.RemoteUpgradeResponse_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.RemoteUpgradeResponse)
  ))
_sym_db.RegisterMessage(RemoteUpgradeResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\032RemoteUpgradeResponseProto'))
# @@protoc_insertion_point(module_scope)
