# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/device2cloud/common/RemoteControlResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/device2cloud/common/RemoteControlResponse.proto',
  package='oss.northbound',
  syntax='proto2',
  serialized_pb=_b('\n>oss/northbound/device2cloud/common/RemoteControlResponse.proto\x12\x0eoss.northbound\"\xa6\x01\n\x15RemoteControlResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12O\n\x1cremote_control_response_type\x18\x03 \x01(\x0e\x32).oss.northbound.RemoteControlResponseType\x12\x15\n\rfailureReason\x18\x04 \x01(\t*\x98\x01\n\x19RemoteControlResponseType\x12\x14\n\x10RCONTRT_RECEIVED\x10\x00\x12\x17\n\x13RCONTRT_FINISHED_OK\x10\x01\x12\x1b\n\x17RCONTRT_FINISHED_FAILED\x10\x02\x12\x13\n\x0fRCONTRT_TIMEOUT\x10\x03\x12\x1a\n\x16RCONTRT_INTERNAL_ERROR\x10\x04\x42^\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\x1aRemoteControlResponseProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_REMOTECONTROLRESPONSETYPE = _descriptor.EnumDescriptor(
  name='RemoteControlResponseType',
  full_name='oss.northbound.RemoteControlResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RCONTRT_RECEIVED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RCONTRT_FINISHED_OK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RCONTRT_FINISHED_FAILED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RCONTRT_TIMEOUT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RCONTRT_INTERNAL_ERROR', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=252,
  serialized_end=404,
)
_sym_db.RegisterEnumDescriptor(_REMOTECONTROLRESPONSETYPE)

RemoteControlResponseType = enum_type_wrapper.EnumTypeWrapper(_REMOTECONTROLRESPONSETYPE)
RCONTRT_RECEIVED = 0
RCONTRT_FINISHED_OK = 1
RCONTRT_FINISHED_FAILED = 2
RCONTRT_TIMEOUT = 3
RCONTRT_INTERNAL_ERROR = 4



_REMOTECONTROLRESPONSE = _descriptor.Descriptor(
  name='RemoteControlResponse',
  full_name='oss.northbound.RemoteControlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='oss.northbound.RemoteControlResponse.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='oss.northbound.RemoteControlResponse.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote_control_response_type', full_name='oss.northbound.RemoteControlResponse.remote_control_response_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failureReason', full_name='oss.northbound.RemoteControlResponse.failureReason', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=249,
)

_REMOTECONTROLRESPONSE.fields_by_name['remote_control_response_type'].enum_type = _REMOTECONTROLRESPONSETYPE
DESCRIPTOR.message_types_by_name['RemoteControlResponse'] = _REMOTECONTROLRESPONSE
DESCRIPTOR.enum_types_by_name['RemoteControlResponseType'] = _REMOTECONTROLRESPONSETYPE

RemoteControlResponse = _reflection.GeneratedProtocolMessageType('RemoteControlResponse', (_message.Message,), dict(
  DESCRIPTOR = _REMOTECONTROLRESPONSE,
  __module__ = 'oss.northbound.device2cloud.common.RemoteControlResponse_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.RemoteControlResponse)
  ))
_sym_db.RegisterMessage(RemoteControlResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\032RemoteControlResponseProto'))
# @@protoc_insertion_point(module_scope)
