# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/device2cloud/RemoteOperationResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oss.northbound.device2cloud.common import RemoteConfigurationResponse_pb2 as oss_dot_northbound_dot_device2cloud_dot_common_dot_RemoteConfigurationResponse__pb2
from oss.northbound.device2cloud.common import RemoteControlResponse_pb2 as oss_dot_northbound_dot_device2cloud_dot_common_dot_RemoteControlResponse__pb2
from oss.northbound.device2cloud.common import RemoteUpgradeResponse_pb2 as oss_dot_northbound_dot_device2cloud_dot_common_dot_RemoteUpgradeResponse__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/device2cloud/RemoteOperationResponse.proto',
  package='oss.northbound',
  syntax='proto2',
  serialized_pb=_b('\n9oss/northbound/device2cloud/RemoteOperationResponse.proto\x12\x0eoss.northbound\x1a\x44oss/northbound/device2cloud/common/RemoteConfigurationResponse.proto\x1a>oss/northbound/device2cloud/common/RemoteControlResponse.proto\x1a>oss/northbound/device2cloud/common/RemoteUpgradeResponse.proto\"\xfd\x01\n\x17RemoteOperationResponse\x12R\n\x1dremote_configuration_response\x18\x01 \x01(\x0b\x32+.oss.northbound.RemoteConfigurationResponse\x12\x46\n\x17remote_control_response\x18\x02 \x01(\x0b\x32%.oss.northbound.RemoteControlResponse\x12\x46\n\x17remote_upgrade_response\x18\x03 \x01(\x0b\x32%.oss.northbound.RemoteUpgradeResponseBY\n9com.nextev.pm.oss.common.protobuf.northbound.device2cloudB\x1cRemoteOperationResponseProto')
  ,
  dependencies=[oss_dot_northbound_dot_device2cloud_dot_common_dot_RemoteConfigurationResponse__pb2.DESCRIPTOR,oss_dot_northbound_dot_device2cloud_dot_common_dot_RemoteControlResponse__pb2.DESCRIPTOR,oss_dot_northbound_dot_device2cloud_dot_common_dot_RemoteUpgradeResponse__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REMOTEOPERATIONRESPONSE = _descriptor.Descriptor(
  name='RemoteOperationResponse',
  full_name='oss.northbound.RemoteOperationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='remote_configuration_response', full_name='oss.northbound.RemoteOperationResponse.remote_configuration_response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote_control_response', full_name='oss.northbound.RemoteOperationResponse.remote_control_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote_upgrade_response', full_name='oss.northbound.RemoteOperationResponse.remote_upgrade_response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=529,
)

_REMOTEOPERATIONRESPONSE.fields_by_name['remote_configuration_response'].message_type = oss_dot_northbound_dot_device2cloud_dot_common_dot_RemoteConfigurationResponse__pb2._REMOTECONFIGURATIONRESPONSE
_REMOTEOPERATIONRESPONSE.fields_by_name['remote_control_response'].message_type = oss_dot_northbound_dot_device2cloud_dot_common_dot_RemoteControlResponse__pb2._REMOTECONTROLRESPONSE
_REMOTEOPERATIONRESPONSE.fields_by_name['remote_upgrade_response'].message_type = oss_dot_northbound_dot_device2cloud_dot_common_dot_RemoteUpgradeResponse__pb2._REMOTEUPGRADERESPONSE
DESCRIPTOR.message_types_by_name['RemoteOperationResponse'] = _REMOTEOPERATIONRESPONSE

RemoteOperationResponse = _reflection.GeneratedProtocolMessageType('RemoteOperationResponse', (_message.Message,), dict(
  DESCRIPTOR = _REMOTEOPERATIONRESPONSE,
  __module__ = 'oss.northbound.device2cloud.RemoteOperationResponse_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.RemoteOperationResponse)
  ))
_sym_db.RegisterMessage(RemoteOperationResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n9com.nextev.pm.oss.common.protobuf.northbound.device2cloudB\034RemoteOperationResponseProto'))
# @@protoc_insertion_point(module_scope)
