# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/common/ACDCModule.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/common/ACDCModule.proto',
  package='oss.northbound',
  syntax='proto2',
  serialized_pb=_b('\n&oss/northbound/common/ACDCModule.proto\x12\x0eoss.northbound\"\x99\x03\n\nACDCModule\x12\x11\n\tmodule_id\x18\x01 \x01(\x05\x12\x13\n\x0boutput_volt\x18\x02 \x01(\x02\x12\x16\n\x0eoutput_current\x18\x03 \x01(\x02\x12\x13\n\x0bmodule_temp\x18\x04 \x01(\x05\x12\x15\n\rfailure_state\x18\x05 \x01(\x05\x12\x12\n\nwork_state\x18\x06 \x01(\x05\x12\x11\n\tpfc_state\x18\x07 \x01(\x05\x12\x16\n\x0e\x66\x61n_work_state\x18\x08 \x01(\x05\x12\x17\n\x0f\x64\x63\x64\x63_work_state\x18\t \x01(\x05\x12\x17\n\x0finput_ac_volt_a\x18\n \x01(\x02\x12\x17\n\x0finput_ac_volt_b\x18\x0b \x01(\x02\x12\x17\n\x0finput_ac_volt_c\x18\x0c \x01(\x02\x12\x1a\n\x12output_rated_power\x18\r \x01(\x02\x12\x1c\n\x14output_rated_current\x18\x0e \x01(\x02\x12 \n\x18module_integrated_state1\x18\x0f \x01(\x05\x12 \n\x18module_integrated_state2\x18\x10 \x01(\x05\x42S\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\x0f\x41\x43\x44\x43ModuleProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACDCMODULE = _descriptor.Descriptor(
  name='ACDCModule',
  full_name='oss.northbound.ACDCModule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_id', full_name='oss.northbound.ACDCModule.module_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_volt', full_name='oss.northbound.ACDCModule.output_volt', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_current', full_name='oss.northbound.ACDCModule.output_current', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module_temp', full_name='oss.northbound.ACDCModule.module_temp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failure_state', full_name='oss.northbound.ACDCModule.failure_state', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='work_state', full_name='oss.northbound.ACDCModule.work_state', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pfc_state', full_name='oss.northbound.ACDCModule.pfc_state', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fan_work_state', full_name='oss.northbound.ACDCModule.fan_work_state', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dcdc_work_state', full_name='oss.northbound.ACDCModule.dcdc_work_state', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_ac_volt_a', full_name='oss.northbound.ACDCModule.input_ac_volt_a', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_ac_volt_b', full_name='oss.northbound.ACDCModule.input_ac_volt_b', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_ac_volt_c', full_name='oss.northbound.ACDCModule.input_ac_volt_c', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_rated_power', full_name='oss.northbound.ACDCModule.output_rated_power', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_rated_current', full_name='oss.northbound.ACDCModule.output_rated_current', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module_integrated_state1', full_name='oss.northbound.ACDCModule.module_integrated_state1', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module_integrated_state2', full_name='oss.northbound.ACDCModule.module_integrated_state2', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=468,
)

DESCRIPTOR.message_types_by_name['ACDCModule'] = _ACDCMODULE

ACDCModule = _reflection.GeneratedProtocolMessageType('ACDCModule', (_message.Message,), dict(
  DESCRIPTOR = _ACDCMODULE,
  __module__ = 'oss.northbound.common.ACDCModule_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.ACDCModule)
  ))
_sym_db.RegisterMessage(ACDCModule)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\017ACDCModuleProto'))
# @@protoc_insertion_point(module_scope)
