# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/common/Alarm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/common/Alarm.proto',
  package='oss.northbound.common',
  syntax='proto2',
  serialized_pb=_b('\n!oss/northbound/common/Alarm.proto\x12\x15oss.northbound.common\"\xa9\x01\n\x05\x41larm\x12\x15\n\ralarm_type_id\x18\x01 \x01(\r\x12\x17\n\x0f\x61larm_timestamp\x18\x02 \x01(\x03\x12\x36\n\x0b\x61larm_state\x18\x03 \x01(\x0e\x32!.oss.northbound.common.AlarmState\x12\x38\n\x0c\x61larm_source\x18\x04 \x01(\x0e\x32\".oss.northbound.common.AlarmSource*,\n\nAlarmState\x12\x0f\n\x0b\x41S_INACTIVE\x10\x00\x12\r\n\tAS_ACTIVE\x10\x01**\n\x0b\x41larmSource\x12\r\n\tAS_DEVICE\x10\x00\x12\x0c\n\x08\x41S_CLOUD\x10\x01\x42N\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\nAlarmProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ALARMSTATE = _descriptor.EnumDescriptor(
  name='AlarmState',
  full_name='oss.northbound.common.AlarmState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AS_INACTIVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AS_ACTIVE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=232,
  serialized_end=276,
)
_sym_db.RegisterEnumDescriptor(_ALARMSTATE)

AlarmState = enum_type_wrapper.EnumTypeWrapper(_ALARMSTATE)
_ALARMSOURCE = _descriptor.EnumDescriptor(
  name='AlarmSource',
  full_name='oss.northbound.common.AlarmSource',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AS_DEVICE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AS_CLOUD', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=278,
  serialized_end=320,
)
_sym_db.RegisterEnumDescriptor(_ALARMSOURCE)

AlarmSource = enum_type_wrapper.EnumTypeWrapper(_ALARMSOURCE)
AS_INACTIVE = 0
AS_ACTIVE = 1
AS_DEVICE = 0
AS_CLOUD = 1



_ALARM = _descriptor.Descriptor(
  name='Alarm',
  full_name='oss.northbound.common.Alarm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alarm_type_id', full_name='oss.northbound.common.Alarm.alarm_type_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarm_timestamp', full_name='oss.northbound.common.Alarm.alarm_timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarm_state', full_name='oss.northbound.common.Alarm.alarm_state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarm_source', full_name='oss.northbound.common.Alarm.alarm_source', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=230,
)

_ALARM.fields_by_name['alarm_state'].enum_type = _ALARMSTATE
_ALARM.fields_by_name['alarm_source'].enum_type = _ALARMSOURCE
DESCRIPTOR.message_types_by_name['Alarm'] = _ALARM
DESCRIPTOR.enum_types_by_name['AlarmState'] = _ALARMSTATE
DESCRIPTOR.enum_types_by_name['AlarmSource'] = _ALARMSOURCE

Alarm = _reflection.GeneratedProtocolMessageType('Alarm', (_message.Message,), dict(
  DESCRIPTOR = _ALARM,
  __module__ = 'oss.northbound.common.Alarm_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.common.Alarm)
  ))
_sym_db.RegisterMessage(Alarm)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\nAlarmProto'))
# @@protoc_insertion_point(module_scope)
