# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/common/CommonBasicInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/common/CommonBasicInfo.proto',
  package='oss.northbound.common',
  syntax='proto2',
  serialized_pb=_b('\n+oss/northbound/common/CommonBasicInfo.proto\x12\x15oss.northbound.common\"_\n\x0f\x43ommonBasicInfo\x12\x18\n\x10software_version\x18\x01 \x01(\t\x12\x18\n\x10hardware_version\x18\x02 \x01(\t\x12\x18\n\x10\x66irmware_version\x18\x03 \x01(\tBX\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\x14\x43ommonBasicInfoProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMMONBASICINFO = _descriptor.Descriptor(
  name='CommonBasicInfo',
  full_name='oss.northbound.common.CommonBasicInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='software_version', full_name='oss.northbound.common.CommonBasicInfo.software_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hardware_version', full_name='oss.northbound.common.CommonBasicInfo.hardware_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firmware_version', full_name='oss.northbound.common.CommonBasicInfo.firmware_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['CommonBasicInfo'] = _COMMONBASICINFO

CommonBasicInfo = _reflection.GeneratedProtocolMessageType('CommonBasicInfo', (_message.Message,), dict(
  DESCRIPTOR = _COMMONBASICINFO,
  __module__ = 'oss.northbound.common.CommonBasicInfo_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.common.CommonBasicInfo)
  ))
_sym_db.RegisterMessage(CommonBasicInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\024CommonBasicInfoProto'))
# @@protoc_insertion_point(module_scope)
