# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/common/ConnectivityState.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/common/ConnectivityState.proto',
  package='oss.northbound.common',
  syntax='proto2',
  serialized_pb=_b('\n-oss/northbound/common/ConnectivityState.proto\x12\x15oss.northbound.common\"\xd2\x01\n\x11\x43onnectivityState\x12@\n\x10network_operator\x18\x01 \x01(\x0e\x32&.oss.northbound.common.NetworkOperator\x12\x38\n\x0cnetwork_type\x18\x02 \x01(\x0e\x32\".oss.northbound.common.NetworkType\x12\r\n\x05iccid\x18\x03 \x01(\t\x12\x32\n\twifi_info\x18\x04 \x01(\x0b\x32\x1f.oss.northbound.common.WifiInfo\"e\n\x08WifiInfo\x12\x12\n\nis_enabled\x18\x01 \x01(\x08\x12\x11\n\thas_fault\x18\x02 \x01(\x08\x12\x14\n\x0cis_broadcast\x18\x03 \x01(\x08\x12\x1c\n\x14is_access_info_match\x18\x04 \x01(\x08*q\n\x0fNetworkOperator\x12\x13\n\x0fNO_CHINA_MOBILE\x10\x00\x12\x13\n\x0fNO_CHINA_UNICOM\x10\x01\x12\x14\n\x10NO_CHINA_TELECOM\x10\x02\x12\r\n\x08NO_OTHER\x10\xfe\x01\x12\x0f\n\nNO_UNKNOWN\x10\xff\x01*m\n\x0bNetworkType\x12\x0b\n\x07NT_RJ45\x10\x00\x12\x0f\n\x0bNT_RADIO_2G\x10\x01\x12\x0f\n\x0bNT_RADIO_3G\x10\x02\x12\x0f\n\x0bNT_RADIO_4G\x10\x03\x12\r\n\x08NT_OTHER\x10\xfe\x01\x12\x0f\n\nNT_UNKNOWN\x10\xff\x01\x42Z\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\x16\x43onnectivityStateProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_NETWORKOPERATOR = _descriptor.EnumDescriptor(
  name='NetworkOperator',
  full_name='oss.northbound.common.NetworkOperator',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_CHINA_MOBILE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_CHINA_UNICOM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_CHINA_TELECOM', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_OTHER', index=3, number=254,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_UNKNOWN', index=4, number=255,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=388,
  serialized_end=501,
)
_sym_db.RegisterEnumDescriptor(_NETWORKOPERATOR)

NetworkOperator = enum_type_wrapper.EnumTypeWrapper(_NETWORKOPERATOR)
_NETWORKTYPE = _descriptor.EnumDescriptor(
  name='NetworkType',
  full_name='oss.northbound.common.NetworkType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NT_RJ45', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NT_RADIO_2G', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NT_RADIO_3G', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NT_RADIO_4G', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NT_OTHER', index=4, number=254,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NT_UNKNOWN', index=5, number=255,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=503,
  serialized_end=612,
)
_sym_db.RegisterEnumDescriptor(_NETWORKTYPE)

NetworkType = enum_type_wrapper.EnumTypeWrapper(_NETWORKTYPE)
NO_CHINA_MOBILE = 0
NO_CHINA_UNICOM = 1
NO_CHINA_TELECOM = 2
NO_OTHER = 254
NO_UNKNOWN = 255
NT_RJ45 = 0
NT_RADIO_2G = 1
NT_RADIO_3G = 2
NT_RADIO_4G = 3
NT_OTHER = 254
NT_UNKNOWN = 255



_CONNECTIVITYSTATE = _descriptor.Descriptor(
  name='ConnectivityState',
  full_name='oss.northbound.common.ConnectivityState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='network_operator', full_name='oss.northbound.common.ConnectivityState.network_operator', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='network_type', full_name='oss.northbound.common.ConnectivityState.network_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iccid', full_name='oss.northbound.common.ConnectivityState.iccid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wifi_info', full_name='oss.northbound.common.ConnectivityState.wifi_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=283,
)


_WIFIINFO = _descriptor.Descriptor(
  name='WifiInfo',
  full_name='oss.northbound.common.WifiInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_enabled', full_name='oss.northbound.common.WifiInfo.is_enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='has_fault', full_name='oss.northbound.common.WifiInfo.has_fault', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_broadcast', full_name='oss.northbound.common.WifiInfo.is_broadcast', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_access_info_match', full_name='oss.northbound.common.WifiInfo.is_access_info_match', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=386,
)

_CONNECTIVITYSTATE.fields_by_name['network_operator'].enum_type = _NETWORKOPERATOR
_CONNECTIVITYSTATE.fields_by_name['network_type'].enum_type = _NETWORKTYPE
_CONNECTIVITYSTATE.fields_by_name['wifi_info'].message_type = _WIFIINFO
DESCRIPTOR.message_types_by_name['ConnectivityState'] = _CONNECTIVITYSTATE
DESCRIPTOR.message_types_by_name['WifiInfo'] = _WIFIINFO
DESCRIPTOR.enum_types_by_name['NetworkOperator'] = _NETWORKOPERATOR
DESCRIPTOR.enum_types_by_name['NetworkType'] = _NETWORKTYPE

ConnectivityState = _reflection.GeneratedProtocolMessageType('ConnectivityState', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIVITYSTATE,
  __module__ = 'oss.northbound.common.ConnectivityState_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.common.ConnectivityState)
  ))
_sym_db.RegisterMessage(ConnectivityState)

WifiInfo = _reflection.GeneratedProtocolMessageType('WifiInfo', (_message.Message,), dict(
  DESCRIPTOR = _WIFIINFO,
  __module__ = 'oss.northbound.common.ConnectivityState_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.common.WifiInfo)
  ))
_sym_db.RegisterMessage(WifiInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\026ConnectivityStateProto'))
# @@protoc_insertion_point(module_scope)
