# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/common/DeviceState.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/common/DeviceState.proto',
  package='oss.northbound.common',
  syntax='proto2',
  serialized_pb=_b('\n\'oss/northbound/common/DeviceState.proto\x12\x15oss.northbound.common*\\\n\x10\x44\x65viceFaultState\x12\x10\n\x0c\x44\x46S_NO_FAULT\x10\x00\x12\x0f\n\x0b\x44\x46S_WARNING\x10\x01\x12\r\n\tDFS_FAULT\x10\x02\x12\x16\n\x12\x44\x46S_CRITICAL_FAULT\x10\x03*8\n\x0f\x43onnectionState\x12\x13\n\x0f\x43S_DISCONNECTED\x10\x00\x12\x10\n\x0c\x43S_CONNECTED\x10\x01\x42T\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\x10\x44\x65viceStateProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DEVICEFAULTSTATE = _descriptor.EnumDescriptor(
  name='DeviceFaultState',
  full_name='oss.northbound.common.DeviceFaultState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DFS_NO_FAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DFS_WARNING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DFS_FAULT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DFS_CRITICAL_FAULT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=66,
  serialized_end=158,
)
_sym_db.RegisterEnumDescriptor(_DEVICEFAULTSTATE)

DeviceFaultState = enum_type_wrapper.EnumTypeWrapper(_DEVICEFAULTSTATE)
_CONNECTIONSTATE = _descriptor.EnumDescriptor(
  name='ConnectionState',
  full_name='oss.northbound.common.ConnectionState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CS_DISCONNECTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CS_CONNECTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=160,
  serialized_end=216,
)
_sym_db.RegisterEnumDescriptor(_CONNECTIONSTATE)

ConnectionState = enum_type_wrapper.EnumTypeWrapper(_CONNECTIONSTATE)
DFS_NO_FAULT = 0
DFS_WARNING = 1
DFS_FAULT = 2
DFS_CRITICAL_FAULT = 3
CS_DISCONNECTED = 0
CS_CONNECTED = 1


DESCRIPTOR.enum_types_by_name['DeviceFaultState'] = _DEVICEFAULTSTATE
DESCRIPTOR.enum_types_by_name['ConnectionState'] = _CONNECTIONSTATE


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\020DeviceStateProto'))
# @@protoc_insertion_point(module_scope)
