# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/common/ElectricMeter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/common/ElectricMeter.proto',
  package='oss.northbound',
  syntax='proto2',
  serialized_pb=_b('\n)oss/northbound/common/ElectricMeter.proto\x12\x0eoss.northbound\"\x96\x03\n\rElectricMeter\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tvoltage_a\x18\x02 \x01(\x02\x12\x11\n\tvoltage_b\x18\x03 \x01(\x02\x12\x11\n\tvoltage_c\x18\x04 \x01(\x02\x12\x11\n\tcurrent_a\x18\x05 \x01(\x02\x12\x11\n\tcurrent_b\x18\x06 \x01(\x02\x12\x11\n\tcurrent_c\x18\x07 \x01(\x02\x12\r\n\x05power\x18\x08 \x01(\x02\x12\x14\n\x0cpower_factor\x18\t \x01(\x02\x12\x13\n\x0b\x65lectricity\x18\n \x01(\x02\x12\x14\n\x0cis_connected\x18\x0b \x01(\x08\x12\x1c\n\x14peak_electric_energy\x18\x0c \x01(\x01\x12\x1c\n\x14\x66lat_electric_energy\x18\r \x01(\x01\x12\x1e\n\x16valley_electric_energy\x18\x0e \x01(\x01\x12\x1d\n\x15total_electric_energy\x18\x0f \x01(\x01\x12\x14\n\x0c\x61\x63tive_power\x18\x10 \x01(\x02\x12\x16\n\x0ereactive_power\x18\x11 \x01(\x02\x12\x0e\n\x06\x65nergy\x18\x12 \x01(\x01\x42I\n3com.nextev.pm.oss.common.protobuf.northbound.commonB\x12\x45lectricMeterProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ELECTRICMETER = _descriptor.Descriptor(
  name='ElectricMeter',
  full_name='oss.northbound.ElectricMeter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='oss.northbound.ElectricMeter.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_a', full_name='oss.northbound.ElectricMeter.voltage_a', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_b', full_name='oss.northbound.ElectricMeter.voltage_b', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage_c', full_name='oss.northbound.ElectricMeter.voltage_c', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_a', full_name='oss.northbound.ElectricMeter.current_a', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_b', full_name='oss.northbound.ElectricMeter.current_b', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_c', full_name='oss.northbound.ElectricMeter.current_c', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='oss.northbound.ElectricMeter.power', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power_factor', full_name='oss.northbound.ElectricMeter.power_factor', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='electricity', full_name='oss.northbound.ElectricMeter.electricity', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_connected', full_name='oss.northbound.ElectricMeter.is_connected', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='peak_electric_energy', full_name='oss.northbound.ElectricMeter.peak_electric_energy', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flat_electric_energy', full_name='oss.northbound.ElectricMeter.flat_electric_energy', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valley_electric_energy', full_name='oss.northbound.ElectricMeter.valley_electric_energy', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_electric_energy', full_name='oss.northbound.ElectricMeter.total_electric_energy', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_power', full_name='oss.northbound.ElectricMeter.active_power', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reactive_power', full_name='oss.northbound.ElectricMeter.reactive_power', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='energy', full_name='oss.northbound.ElectricMeter.energy', index=17,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=468,
)

DESCRIPTOR.message_types_by_name['ElectricMeter'] = _ELECTRICMETER

ElectricMeter = _reflection.GeneratedProtocolMessageType('ElectricMeter', (_message.Message,), dict(
  DESCRIPTOR = _ELECTRICMETER,
  __module__ = 'oss.northbound.common.ElectricMeter_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.ElectricMeter)
  ))
_sym_db.RegisterMessage(ElectricMeter)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3com.nextev.pm.oss.common.protobuf.northbound.commonB\022ElectricMeterProto'))
# @@protoc_insertion_point(module_scope)
