# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/common/PowerAllocation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/common/PowerAllocation.proto',
  package='oss.northbound',
  syntax='proto2',
  serialized_pb=_b('\n+oss/northbound/common/PowerAllocation.proto\x12\x0eoss.northbound\"\x99\x01\n\x0fPowerAllocation\x12\x13\n\x0b\x63\x61\x62inet_num\x18\x01 \x01(\x05\x12>\n\nallocation\x18\x02 \x03(\x0b\x32*.oss.northbound.PowerAllocation.Allocation\x1a\x31\n\nAllocation\x12\x0f\n\x07pdu_num\x18\x01 \x01(\t\x12\x12\n\nmodule_num\x18\x02 \x01(\x05\x42X\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\x14PowerAllocationProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POWERALLOCATION_ALLOCATION = _descriptor.Descriptor(
  name='Allocation',
  full_name='oss.northbound.PowerAllocation.Allocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pdu_num', full_name='oss.northbound.PowerAllocation.Allocation.pdu_num', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module_num', full_name='oss.northbound.PowerAllocation.Allocation.module_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=217,
)

_POWERALLOCATION = _descriptor.Descriptor(
  name='PowerAllocation',
  full_name='oss.northbound.PowerAllocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cabinet_num', full_name='oss.northbound.PowerAllocation.cabinet_num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='allocation', full_name='oss.northbound.PowerAllocation.allocation', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_POWERALLOCATION_ALLOCATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=217,
)

_POWERALLOCATION_ALLOCATION.containing_type = _POWERALLOCATION
_POWERALLOCATION.fields_by_name['allocation'].message_type = _POWERALLOCATION_ALLOCATION
DESCRIPTOR.message_types_by_name['PowerAllocation'] = _POWERALLOCATION

PowerAllocation = _reflection.GeneratedProtocolMessageType('PowerAllocation', (_message.Message,), dict(

  Allocation = _reflection.GeneratedProtocolMessageType('Allocation', (_message.Message,), dict(
    DESCRIPTOR = _POWERALLOCATION_ALLOCATION,
    __module__ = 'oss.northbound.common.PowerAllocation_pb2'
    # @@protoc_insertion_point(class_scope:oss.northbound.PowerAllocation.Allocation)
    ))
  ,
  DESCRIPTOR = _POWERALLOCATION,
  __module__ = 'oss.northbound.common.PowerAllocation_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.PowerAllocation)
  ))
_sym_db.RegisterMessage(PowerAllocation)
_sym_db.RegisterMessage(PowerAllocation.Allocation)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\024PowerAllocationProto'))
# @@protoc_insertion_point(module_scope)
