# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/common/ServiceParam.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/common/ServiceParam.proto',
  package='oss.northbound.common',
  syntax='proto2',
  serialized_pb=_b('\n(oss/northbound/common/ServiceParam.proto\x12\x15oss.northbound.common\"\x0e\n\x0cServiceParam*+\n\x0cServiceEvent\x12\x0c\n\x08SE_START\x10\x00\x12\r\n\tSE_FINISH\x10\x01*0\n\x13ServiceFinishResult\x12\r\n\tSFR_ERROR\x10\x00\x12\n\n\x06SFR_OK\x10\x01\x42U\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\x11ServiceParamProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SERVICEEVENT = _descriptor.EnumDescriptor(
  name='ServiceEvent',
  full_name='oss.northbound.common.ServiceEvent',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SE_START', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SE_FINISH', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=83,
  serialized_end=126,
)
_sym_db.RegisterEnumDescriptor(_SERVICEEVENT)

ServiceEvent = enum_type_wrapper.EnumTypeWrapper(_SERVICEEVENT)
_SERVICEFINISHRESULT = _descriptor.EnumDescriptor(
  name='ServiceFinishResult',
  full_name='oss.northbound.common.ServiceFinishResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SFR_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SFR_OK', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=128,
  serialized_end=176,
)
_sym_db.RegisterEnumDescriptor(_SERVICEFINISHRESULT)

ServiceFinishResult = enum_type_wrapper.EnumTypeWrapper(_SERVICEFINISHRESULT)
SE_START = 0
SE_FINISH = 1
SFR_ERROR = 0
SFR_OK = 1



_SERVICEPARAM = _descriptor.Descriptor(
  name='ServiceParam',
  full_name='oss.northbound.common.ServiceParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['ServiceParam'] = _SERVICEPARAM
DESCRIPTOR.enum_types_by_name['ServiceEvent'] = _SERVICEEVENT
DESCRIPTOR.enum_types_by_name['ServiceFinishResult'] = _SERVICEFINISHRESULT

ServiceParam = _reflection.GeneratedProtocolMessageType('ServiceParam', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEPARAM,
  __module__ = 'oss.northbound.common.ServiceParam_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.common.ServiceParam)
  ))
_sym_db.RegisterMessage(ServiceParam)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n@com.nextev.pm.oss.common.protobuf.northbound.device2cloud.commonB\021ServiceParamProto'))
# @@protoc_insertion_point(module_scope)
