# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oss/northbound/common/WaterCoolingSystem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oss/northbound/common/WaterCoolingSystem.proto',
  package='oss.northbound',
  syntax='proto2',
  serialized_pb=_b('\n.oss/northbound/common/WaterCoolingSystem.proto\x12\x0eoss.northbound\"\xbf\x02\n\x12WaterCoolingSystem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1f\n\x17inlet_water_temperature\x18\x02 \x01(\x02\x12 \n\x18outlet_water_temperature\x18\x03 \x01(\x02\x12%\n\x1dpump_outlet_water_temperature\x18\x04 \x01(\x02\x12\x18\n\x10\x65xhaust_pressure\x18\x05 \x01(\x02\x12\x18\n\x10suction_pressure\x18\x06 \x01(\x02\x12\x1b\n\x13\x65xhaust_temperature\x18\x07 \x01(\x02\x12\x1b\n\x13suction_temperature\x18\x08 \x01(\x02\x12\x18\n\x10is_refrigeration\x18\t \x01(\x08\x12\x12\n\nis_heating\x18\n \x01(\x08\x12\x17\n\x0fis_pump_running\x18\x0b \x01(\x08\x42N\n3com.nextev.pm.oss.common.protobuf.northbound.commonB\x17WaterCoolingSystemProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WATERCOOLINGSYSTEM = _descriptor.Descriptor(
  name='WaterCoolingSystem',
  full_name='oss.northbound.WaterCoolingSystem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='oss.northbound.WaterCoolingSystem.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inlet_water_temperature', full_name='oss.northbound.WaterCoolingSystem.inlet_water_temperature', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outlet_water_temperature', full_name='oss.northbound.WaterCoolingSystem.outlet_water_temperature', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pump_outlet_water_temperature', full_name='oss.northbound.WaterCoolingSystem.pump_outlet_water_temperature', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exhaust_pressure', full_name='oss.northbound.WaterCoolingSystem.exhaust_pressure', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='suction_pressure', full_name='oss.northbound.WaterCoolingSystem.suction_pressure', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exhaust_temperature', full_name='oss.northbound.WaterCoolingSystem.exhaust_temperature', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='suction_temperature', full_name='oss.northbound.WaterCoolingSystem.suction_temperature', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_refrigeration', full_name='oss.northbound.WaterCoolingSystem.is_refrigeration', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_heating', full_name='oss.northbound.WaterCoolingSystem.is_heating', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_pump_running', full_name='oss.northbound.WaterCoolingSystem.is_pump_running', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=386,
)

DESCRIPTOR.message_types_by_name['WaterCoolingSystem'] = _WATERCOOLINGSYSTEM

WaterCoolingSystem = _reflection.GeneratedProtocolMessageType('WaterCoolingSystem', (_message.Message,), dict(
  DESCRIPTOR = _WATERCOOLINGSYSTEM,
  __module__ = 'oss.northbound.common.WaterCoolingSystem_pb2'
  # @@protoc_insertion_point(class_scope:oss.northbound.WaterCoolingSystem)
  ))
_sym_db.RegisterMessage(WaterCoolingSystem)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3com.nextev.pm.oss.common.protobuf.northbound.commonB\027WaterCoolingSystemProto'))
# @@protoc_insertion_point(module_scope)
